openapi: 3.0.3
info:
  title: SETRAG Inventory API (draft)
  version: 0.1.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200': { description: OK }
  /stations:
    get:
      summary: Lister les gares
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Station'
  /trips:
    get:
      summary: Lister les trajets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
components:
  schemas:
    Station:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        latitude: { type: number }
        longitude: { type: number }
    Trip:
      type: object
      properties:
        id: { type: string }
        origin_station_id: { type: string }
        destination_station_id: { type: string }
        departure_time: { type: string, format: date-time }
        arrival_time: { type: string, format: date-time }


